[MIRROR] Hard resets Icons to Polaris
CHOMPStation2/CHOMPStation2 pull request #1549
Opened 2021-03-10 00:06 UTC by CHOMPStationBot

Original PR: https://github.com/VOREStation/VOREStation/pull/9885
--------------------
Okay this was stress-inducing enough that I am going to stick to just icon/obj for now.

2021-03-10 16:54 UTC, Shadow-Quill requested changes

2021-03-10 16:54 UTC, Shadow-Quill commented on vorestation.dme
> +<<<<<<< HEAD
```suggestion
<<<<<<< HEAD
```

2021-03-10 16:54 UTC, Shadow-Quill commented on vorestation.dme
> +>>>>>>> b14abd6164... Merge pull request #9885 from Novacat/nova-basicfixes
```suggestion
#include "code\modules\news\news_init.dm"
#include "code\modules\news\newspaper.dm"
#include "code\modules\news\newspaper_layout.dm"
```

2021-03-11 05:44 UTC, Darlantanis commented
Implemented by #1571

2021-03-11 05:44 UTC, closed without merging