Lowers the cost of producing liquids, increase the max capacity & indents a comment
CHOMPStation2/CHOMPStation2 pull request #2779
Opened 2021-08-12 06:17 UTC by lbnesquik

## About this PR
It brings the cost of producing any liquid from 15 to 5.
It increases the max capacity to 200.
It fixes a little indent so things look prettier

## Why is this good for the game
Liquids currently give you really, really poor levels of nutrition, and feeding scenes are rare. It is just silly to me that we have to spend half our nutrition on it. 
Max capacity increase is for those people who want to actually have a lot of liquid. I can't see this breaking anything or unbalancing anything.

2021-08-13 07:30 UTC, Razgriz1032 commented
Noodleserg warns that increased max cap will fuck with the examine text

2021-08-14 02:51 UTC, Darlantanis commented
I don't see an issue with this given the general uselessness of nutrition but if examine options are affected by this variable then they need corresponding tweaks to avoid breaking things.

2021-08-16 10:17 UTC, Verkister commented
I think the gen_time var means affects time, not capacity, and probably shouldn't be doubled there.

2021-08-16 10:27 UTC, Verkister commented
Also the examine amounts are located in living_ch.dm line 48 and so on.

2021-08-16 10:53 UTC, Verkister requested changes
custom_max_volume seems to be the customizable capacity setting and shouldn't be used as a solid cap. Looks like just changing the number on the if("b_liq_reagent_capacity") and create_reagents parts to 200 would have been enough to raise the cap

2021-08-16 10:53 UTC, Verkister commented on code/modules/vore/eating/vorepanel_vr.dm
> +			var/new_new_custom_vol = CLAMP(new_custom_vol, 10, host.vore_selected.custom_max_volume)
Also hardcode these to 200 if you don't wanna end up every future setting to be limited to the earlier one, such as never being able to set the belly above 50 unit again if you happen to lower that even once.

2021-08-16 10:53 UTC, Verkister commented on code/modules/vore/eating/vorepanel_vr.dm
> +					host.vore_selected.gen_time = 286
Doubling these will only double the amount of time it takes to produce a single unit and that would mess things up.

2021-08-16 10:53 UTC, Verkister commented on code/modules/vore/eating/belly_obj_vr.dm
> +	create_reagents(custom_max_volume)	//CHOMP So we can have some liquids in bellies
Might want to hardcode this too in order to avoid things becoming impossible to increase after decreasing it even once.

2021-08-16 11:36 UTC, Verkister commented
And while all the other available liquid options might be near worthless on nutrition, honey still gives 10 per unit. I'd personally prefer to have some costlier liquid options too because I often tend to use it to get rid of some extra lard without having to spam the gym for hours, ~~and on one character as a way to produce something fuffed as a precious non-abundant resource~~, but then again I've been planning to add some more options for that myself anyway

2021-08-16 12:48 UTC, lbnesquik commented
This change shouldn't be so hard. Me angry.

2021-08-24 22:28 UTC, lbnesquik commented
This PR bloated out of the reach i appreciate. I'll get back to this another time.

2021-08-24 22:28 UTC, closed without merging