Rocket Launcher Damage Increase
CHOMPStation2/CHOMPStation2 pull request #3733
Opened 2022-02-20 22:19 UTC by harry3124

Damage has been severely low on the previous value.
Splash damage/radius has been decreased to compensate.

2022-02-20 22:47 UTC, Rykka-Stormheart requested changes
The proc should be left in, admin log + messages can safely be removed, but if you're removing the entire proc, remove the ..() too

2022-02-20 22:47 UTC, Rykka-Stormheart commented on code/modules/projectiles/guns/launcher/rocket.dm
> -/obj/item/weapon/gun/launcher/rocket/handle_post_fire(mob/user, atom/target)
This should be left in (not the admin log/message, just the proc) - launchers may need to do a callback post-fire, but if you're set on removing it, remove the ..() below.

2022-02-21 03:51 UTC, Cyrelius commented
The armour penetration might be a little much, but this looks very good overall.  My worry is one-shotting people, it's not fun when you get oneshot-killed.

2022-03-01 09:27 UTC, Razgriz1032 commented
To do that much armor pen and have a 4 tile explosion radius would be too much.

I'd honestly make multiple rocket types, HE with no armor pen and the 4 tile radius and lower damage, and HEAT with large pen and small radius and high damage.

2022-03-01 09:28 UTC, Rykka-Stormheart commented
> To do that much armor pen and have a 4 tile explosion radius would be too much.
> 
> I'd honestly make multiple rocket types, HE with no armor pen and the 4 tile radius and lower damage, and HEAT with large pen and small radius and high damage.

This would be awesome, choose your ammo based on situation, rather than one-size-beats-all.

2022-03-21 04:29 UTC, Razgriz1032 commented
Ahh, missing comments. See this for comments guidelines. 
https://github.com/CHOMPStation2/CHOMPStation2/blob/3fe84f61e8fff3cc962c803207b2f0acf80d3576/.github/CONTRIBUTING.md

==============
When changing any code in any stock Polaris .DM file, you must mark your changes:
For single-line changes: //CHOMPEdit - "Explanation" (Edit can also be Add for new lines or Removal if you are commenting the line out)
For multi-line additions: //CHOMPEdit - "Explanation" and then at the bottom of your changes, //CHOMPEdit End
For multi-line removals: Use a block comment (/* xxx */) to comment out the existing code block (do not modify whitespace more than necessary) and at the start, it should contain /* CHOMP Removal - "Reason"
==============

2022-06-06 22:35 UTC, closed without merging