Explorationedits
CHOMPStation2/CHOMPStation2 pull request #4143
Opened 2022-04-23 20:12 UTC by Tasald

Adds a new set of exploration armor plates. adds various items to the exploration vendor, and lowers the price of the carbine.

Will probably need discussion on items and the armor.

2022-04-23 21:16 UTC, Tasald commented
gona need to get input on this probably, for the new armor, and the denecrotizer atleast.

2022-04-24 03:28 UTC, Tasald commented
not sure why the ecig thing is still in this.. it shouldnt be

2022-04-28 23:30 UTC, Rykka-Stormheart requested changes
These things need correcting for your PR to pass checks, but otherwise it appears fine.

2022-04-28 23:30 UTC, Rykka-Stormheart commented on code/modules/clothing/under/accessories/armor.dm
> +armorsoak = list(melee = 10, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0) //CHOMPADD
Needs indented to match.

2022-04-28 23:30 UTC, Rykka-Stormheart commented on code/modules/mining/ore_redemption_machine/survey_vendor.dm
> +		EQUIPMENT("Defense Equipment - Holdout Phaser", 		obj/item/weapon/gun/energy/locked/frontier/holdout,				75), //CHOMPADD
```suggestion
		EQUIPMENT("Defense Equipment - Holdout Phaser", 		/obj/item/weapon/gun/energy/locked/frontier/holdout,				75), //CHOMPADD
```

2022-04-28 23:30 UTC, Rykka-Stormheart commented on code/modules/clothing/under/accessories/armor.dm
> +	/obj/item/clothing/accessory/armor/legguards/explorer/adv //CHOMPADD
```suggestion
/obj/item/clothing/accessory/armor/legguards/explorer/adv //CHOMPADD
```

2022-04-29 00:25 UTC, Cyrelius commented
You made the weapons too cheap in the vendor, and they should be at least double.

Regarding the armour, we need to have an internal discussion, as those plates you add are practically as good as armor that security gets in the lethal section of the **armoury**, but at the same time, I consider what's in the armoury to be trash.  It definitely can't go in without something else changing.  That being said, I wouldn't mind them being able to get better armour from the vendor, but we'll have to see on how good that'll be.

The denecrotizer is a bad idea.  That's something that medical should possibly have mapped in, and science should be able to make, and shouldn't be in a vendor at all, much less one restricted to only explorers.

2022-04-29 00:30 UTC, BlackMajor commented on code/modules/clothing/under/accessories/armor.dm
> +	/obj/item/clothing/accessory/armor/armorplate/explorer/adv //CHOMPADD
You've got a tab here that you shouldn't

2022-04-29 00:32 UTC, BlackMajor commented
Also since we have a modular folder now, I'm requesting you move the new armor you've put into 'code/modules/clothing/under/accessories/armor.dm' and create a file under 'modular_chomp/code/modules/clothing/under/accessories/armor.dm' for them. No need for chomp comments since it's the modular folder.

2022-05-01 18:52 UTC, Tasald commented
made changes from staff comments, not putting the new folder yet, going to wait until I get what stats are ok for it.

2022-05-20 10:04 UTC, Razgriz1032 commented
I don't think we'll include the armor in this tho. As soon as the leg guards is fixed, we'll merge it now. The new types of armor, I don't think we'll include in this and it'd need like a separate project.

2022-11-15 06:54 UTC, merged