Kinetic Things and Weird Goggle
CHOMPStation2/CHOMPStation2 pull request #8207
Opened 2024-04-10 18:53 UTC by FluffMedic

Okay

## About The Pull Request

## Changelog

:cl:
add: Added admin spawn set of goggles, one is mesons that can see shaekin, one is a goggle type that's sole purpose is seeing kin
balance: Makes it so the large kinetic weapons don't need wielding since that code is appears broken and I doubt the two very rare items will become broken if they get the kinetic blast effect.
/:cl:

2024-04-14 16:26 UTC, Kazzc commented
I like this a lot, may come in handy with some of my events.

2024-04-14 16:58 UTC, Kashargul commented
Were those tested? Invisibility used here was never defined as plane, so this might runtime horribly.

2024-04-14 17:01 UTC, Kashargul requested changes

2024-04-14 17:01 UTC, Kashargul commented on modular_chomp/code/modules/clothing/glasses/glasses.dm
> +
This is not a plane.

~~enables_planes = list(INVISIBILITY_SHADEKIN)~~


see_invisible = INVISIBILITY_SHADEKIN

2024-04-14 17:01 UTC, Kashargul commented on modular_chomp/code/modules/clothing/glasses/glasses.dm
> +	enables_planes = list(VIS_FULLBRIGHT, VIS_MESONS, INVISIBILITY_SHADEKIN)
enables_planes = list(VIS_FULLBRIGHT, VIS_MESONS, ~~INVISIBILITY_SHADEKIN~~)
see_invisible = INVISIBILITY_SHADEKIN

2024-04-14 18:32 UTC, Kashargul commented on modular_chomp/code/modules/clothing/glasses/glasses.dm
> +	enables_planes = list(VIS_FULLBRIGHT, VIS_MESONS, INVISIBILITY_SHADEKIN)
if making it consistent, SEE_INVISIBILITY_SHADEKIN

create a new define in misc.dm with that name, value 55

2024-04-17 20:20 UTC, Kashargul approved these changes

2024-04-18 17:33 UTC, Raeschen commented
not the keenest on shadekin sight, even if adminspawn

2024-04-19 07:26 UTC, Raeschen commented
IMO, the meson/darksight hybrid shouldn't exist. The sole-shadekin sight glasses ARE ok i guess if only adminspawn, but i really want to keep an ability like this purely to a specialised thing.

2024-04-29 14:06 UTC, merged