[DNM] Port's RS's anti job camping to Anomoly
CHOMPStation2/CHOMPStation2 pull request #8618
Opened 2024-07-04 18:20 UTC by tacoguy7765093

## About The Pull Request

Makes it so that if you played anomoly last shift, you will have to wait 10 minutes the next shift to be able to play again to give other people a chance to play shadekin. This should help with the same people camping the same job slot multiple shifts in the row and gives people that aren't as online a chance to play.

Code is by VerySoft and currently this affects anomaly only, can be put for future jobs.

Do not merge until this strange compile bug is fixed. 
## Changelog

:cl:
add: Added anti-job-camping to Anomalys
/:cl:

2024-07-04 18:38 UTC, Kashargul requested changes

2024-07-04 18:38 UTC, Kashargul commented on code/controllers/subsystems/job.dm
> +		to_world("failed to write to json")
no to_world in live code

2024-07-04 18:38 UTC, Kashargul commented on code/modules/mob/new_player/new_player_vr.dm
> +				to_chat(src,"<span class = 'danger'>[J.title] is not presently selectable because you played as it last round. It will become available to you in [round((CONFIG_GET(number/job_camp_time_limit - r
1 opening bracket too much

2024-07-04 19:24 UTC, tacoguy7765093 commented
Code has not been tested yet, will do so when I go home today, so I'll keep DNM for a couple of hours

2024-07-06 21:08 UTC, Kashargul requested changes

2024-07-06 21:08 UTC, Kashargul commented on code/game/machinery/computer/timeclock_vr.dm
> +				to_chat(src,"<span class = 'danger'>[newjob.title] is not presently selectable because you played as it last round. It will become available to you in [round((CONFIG_GET(number/job_camp_time_limi
src can't work here.

2024-07-06 21:08 UTC, Kashargul commented on code/modules/mob/new_player/new_player_vr.dm
> +				to_chat(src,"<span class = 'danger'>[J.title] is not presently selectable because you played as it last round. It will become available to you in [round(CONFIG_GET(number/job_camp_time_limit - ro
src can't work here

2024-07-07 02:18 UTC, Kashargul approved these changes

2024-07-18 05:52 UTC, merged