Makes sure that souls caught in the vore soulcatcher actually have their prefs.
CHOMPStation2/CHOMPStation2 pull request #8772
Opened 2024-08-11 19:57 UTC by RandoGuy999

## About The Pull Request
After testing the vore soulcatcher locally, I found that caught souls didn't have their prefs after being caught (or at least the ones that matter for a caught soul). This PR fixes that.
Hopefully the proc I called is fine for this.

## Changelog

:cl:
fix: Souls caught in the vore soulcatcher will now actually have their prefs.
/:cl:

2024-08-11 20:36 UTC, Kashargul commented
Also this is usually redundant there's a hook that is called which copies the prefs. So this will make no difference.

2024-08-11 22:30 UTC, Kashargul requested changes

2024-08-12 14:03 UTC, RandoGuy999 commented on modular_chomp/code/modules/vore/eating/soulcatcher.dm
> +	brainmob.copy_from_prefs_vr()//CHOMPEDIT - The caught soul needs their prefs and only their prefs
Edits made.

2024-08-12 14:11 UTC, Kashargul approved these changes

2024-08-12 17:08 UTC, merged