Food Replicator
CHOMPStation2/CHOMPStation2 pull request #8873
Opened 2024-08-31 17:22 UTC by TheCaramelion

## About The Pull Request

Adds a food replicator machine, along with the circuit to build it. It takes a big chunk of nutriment if not upgraded, and it is also rather slow and power hungry.

To unlock the food, first it **must** be cooked, giving the chef a chance to cook anything they want and then for the crew to replicate it if they want more and the chef is not around.

Science and Engineering can both print this, as long as the minimum research is met.

## Changelog

:cl:
add: Food replicator machine
/:cl:

2024-09-02 22:19 UTC, Kashargul requested changes
There should be a blacklist for some specific food items...

-> food with supermatter reagent

2024-09-04 12:08 UTC, Kashargul commented on modular_chomp/code/game/machinery/food_replicator.dm
> +			if(product_path == /obj/item/weapon/reagent_containers/food/snacks/donkpocket/ascended)
could even check if any food contains supermatter as reagent, so in case anyone adds some new funny food it's handled the same

2024-09-09 11:26 UTC, Kashargul approved these changes
Hmmm, so the donks even need to be heated to be replicable?

2024-09-09 12:04 UTC, TheCaramelion commented
> Hmmm, so the donks even need to be heated to be replicable?

Mostly because of the ascended one, else it would be easy to just replicate it all over

2024-09-24 00:20 UTC, merged