Virology Reworked
CHOMPStation2/CHOMPStation2 pull request #9262
Opened 2024-10-19 14:26 UTC by TheCaramelion

## About The Pull Request

Gets rid of Virus 2 and +10 years old untouched code. Updates the entire diseases system and makes the virology role useful for once.

Advance diseases are engineered by virologists, they can range from useful to dangerous. Virologists can use the new chemicals to improve and evolve their viruses. These new viruses can be cured with specific chemicals, as well as the ones made by the virologists. If a virus has been found, you can check the cure with a simple health analyzer, otherwise the PanDEMIC machine will show anything in it. Viruses will be auto-discovered if they reach half or more in it's stages.

## Changelog

:cl:
add: Virus 1
add: Many effects for the new disease system
add: Chemicals for the new disease system
/:cl:

2024-10-19 15:06 UTC, Skysteak commented
Has a lot of potential! I don't know how to read code very well, but as stated before (and saying again here for the record), I do think maintaining a self cure chance ('toughing it out') , regardless of inaction would be good, even if non-viable for severe viruses. 

I think it is set like this in the PR already, but as before, ensuring viruses poof upon death is good, and ensures that a station struggling to cope with a death virus in say, an event, doesn't just death spiral. Whilst it may seem authentic to a viral outbreak, what it'd essential translate into is just mass resleeving, manual or automatic.

Just in case: Remember the Virus Immunity trait exists!

**On particular virus symptoms:**

-Coughing making you drop small items makes me feel conflicted , but I understand the need for it to actually be disruptive without being fatal. I think it'll come down to the rate it procs (in terms of how it 'feels' in game).

-The Fever Temp Raise; This is once again 'I read code bad' as a question, but will it potentially endanger teshari or people with the cold adapted trait? 

-The Magnetism; Is it just moving silicons about or physically throwing them? Do note that if it's the latter, that A. Borg stuns are a lot more obnoxious than person ones, due to it clearing your hotbar  every time it happens, and B. Whilst armour helps, being thrown into walls is quite nasty, even for silicons. Also I don't think you can do this, but it'd be fun if synths were also affected by it too!

2024-10-19 17:33 UTC, TheCaramelion commented
Most of the viruses are able to be self-healed, there's even a virus effect that clears other virus effects.
Diseases already clear upon death, and I wasn't planning on making any new that would actually work on dead people unless it's for some kind of event or PoI where corpses CAN transmit them.
Virus immunity stays the same and won't infect people, however, it might make asyntomatic carriers.

While all the effects are still being worked on, the ones that were pointed out:
Coughing only works for small items like pens, cups and papers, not much that can be solved with a small click
Fever shouldn't go into lethal temperatures for species that can't handle the heat, it's capped at their max
Magnetism does throw silicons, but the effects won't happen if you're not in sight of the patient with the virus. It won't throw people against walls. Most of the time it would end up in accidental vore

And there will be an affect that will make synthetics be affected, so they can also get the good viruses that a virologist may create

2024-10-27 00:55 UTC, TheCaramelion commented
Needs fixing on Soluna Nexus but the rest should be good to go

2024-10-27 01:38 UTC, Kashargul requested changes

2024-10-27 01:38 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, span_userdanger("[pick("You cringe as a violent pain takes over your body.", "It feels like your body is eating itself inside out.", "IT HURTS.")]"))
spans are defined as
#define span_type(str) ("<span class='type'>" + str + "</span>") so they can be chained and even procs can be used in them. There's no need to use any with "[proc("")]"

Counts for all uses here. The only important is that the function returns only strings

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/hallucigen.dm
> +				to_chat(M, span_warning("<b>[pick("Something is following you.", "You are being watched.", "You hear a whisper in your ear.", "Thumping footsteps slam toward you from nowhere.")]</b>"))
span_boldwarning()

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/spin.dm
> +			to_chat(viewers(A.affected_mob), span_warning("[A.affected_mob.name] struggles violently against their restraints!"))
Can to_chat handle more than one target? It wants 1 usually

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/spin.dm
> +			to_chat(viewers(A.affected_mob), span_warning("[A.affected_mob.name] spins around violently!"))
Can to_chat handle more than one target? It wants 1 usually

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/weigh.dm
> +				to_chat(M, span_warning("<i>[pick("So hungry...", "You'd kill someone for a bite of food...", "Hunger cramps seize you...")]</i>"))
span_italics

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/datums/diseases/food_poisoning.dm
> +					to_chat(affected_mob, "Your stomach lurches painfully")
No sorting span

2024-10-28 16:37 UTC, Kashargul commented on modular_chomp/code/game/machinery/pandemic.dm
> +		to_chat(usr, span_notice("You add the beaker to the machine."))
usr? why not user

2024-10-28 16:45 UTC, Kashargul commented on modular_chomp/code/datums/diseases/advance/symptoms/spin.dm
> +			to_chat(viewers(A.affected_mob), span_warning("[A.affected_mob.name] struggles violently against their restraints!"))
handled in the queue of the subsystem

2024-10-28 19:25 UTC, TheCaramelion commented
Upstream asked for this, upporting

2024-11-06 23:45 UTC, closed without merging