Leashes
CHOMPStation2/CHOMPStation2 pull request #9665
Opened 2024-12-20 19:25 UTC by BigBadE

## About The Pull Request

Adds in leashes, which can be clipped onto collars. When someone is leashed, they can be dragged around by whoever is holding it. A player can leash themselves, allowing anyone to grab onto it and drag them. Leashes can be bought from the Looty vendor. The sprite is ported, as well as the mob tug function (I did not see an equivalent in the code), but the rest of the code is re-written to match our codebase (and possibly slightly fucked up, since I've never used signals or written an item before). Let me know if I should re-sprite the leash.

## Changelog

:cl:
add: Leashes, which can be attached onto collars. Buyable in the Looty vendor.
/:cl:

2024-12-21 00:58 UTC, Kashargul requested changes

2024-12-21 00:58 UTC, Kashargul commented on modular_chomp/code/game/objects/items/leash.dm
> +	if (!istype(human)) {
keep byond style

2024-12-21 07:02 UTC, BigBadE commented on modular_chomp/code/game/objects/items/leash.dm
> +	if (!istype(human)) {
Fixed now

2024-12-22 04:38 UTC, Kashargul requested changes
-> A preference must be created to have players decide if they want to be leashed.
-> OOC escape must work on leashed players.

2024-12-22 05:00 UTC, BigBadE commented
Removing the collar instantly disconnects the leash, would that work, or does it also have to implement OOC escape?
What should this preference be called?

2024-12-22 05:02 UTC, Kashargul commented
> Removing the collar instantly disconnects the leash, would that work, or does it also have to implement OOC escape? What should this preference be called?

Should have the OOC escape button working as it informs admins too.

The pref should go into the misc section, turned off by default and something like "Allow / Disallow Leashing" depending on the current state.

2024-12-26 04:07 UTC, BigBadE commented
Added the OOC escape. If this isn't enough, what about a capture crystal-like popup instead of clouding the prefs menu with another random pref?

2024-12-28 04:33 UTC, Kashargul commented
> Added the OOC escape. If this isn't enough, what about a capture crystal-like popup instead of clouding the prefs menu with another random pref?

Should be enough to prevent mischief.

2024-12-31 03:56 UTC, BigBadE commented
> > Added the OOC escape. If this isn't enough, what about a capture crystal-like popup instead of clouding the prefs menu with another random pref?
> 
> Should be enough to prevent mischief.

Okay, what's left for this to get merged then?

2024-12-31 15:15 UTC, SatinIsle commented
I was talking on the virgo discord about wanting something like this, lol. Kashargul told me to ask, if you are interested in upporting it there, we'd definitely have it too.

2024-12-31 19:16 UTC, BigBadE commented
> I was talking on the virgo discord about wanting something like this, lol. Kashargul told me to ask, if you are interested in upporting it there, we'd definitely have it too.

I have no clue where I'd up-port it to/how y'all want players to access it, but it's just a single file, so anyone else is free to up-port it if they want it.

2024-12-31 19:17 UTC, BigBadE commented
I added a tgui prompt for getting leashed too, couldn't test it without another player though. Can someone try it?

2024-12-31 19:24 UTC, SatinIsle commented
> > I was talking on the virgo discord about wanting something like this, lol. Kashargul told me to ask, if you are interested in upporting it there, we'd definitely have it too.
> 
> I have no clue where I'd up-port it to/how y'all want players to access it, but it's just a single file, so anyone else is free to up-port it if they want it.

I appreciate that! In that case, I'll keep an eye on this one and when it's merged I'll port it up myself, thank you!

2024-12-31 19:29 UTC, Kashargul commented
> > > I was talking on the virgo discord about wanting something like this, lol. Kashargul told me to ask, if you are interested in upporting it there, we'd definitely have it too.
> > 
> > 
> > I have no clue where I'd up-port it to/how y'all want players to access it, but it's just a single file, so anyone else is free to up-port it if they want it.
> 
> I appreciate that! In that case, I'll keep an eye on this one and when it's merged I'll port it up myself, thank you!

please not. I won't merge and deconflict. Then directly pull this upstream.

2025-01-01 19:20 UTC, BigBadE commented
@SatinIsle Are you pulling this upstream?

It also seems like something broke, either that or my testing server was screwed up.

2025-01-01 22:40 UTC, SatinIsle commented
> @SatinIsle Are you pulling this upstream?
> 
> It also seems like something broke, either that or my testing server was screwed up.

I was under the impression that Kashargul was telling me to let him do it, which I'm fine wjth because he knows how to, lol

2025-01-05 21:11 UTC, closed without merging