Event prep stuff!
CHOMPStation2/CHOMPStation2 pull request #9721
Opened 2024-12-29 19:33 UTC by SilencedMP5A5

## About The Pull Request

Event prep stuff! Contents may contain spoilers, if you're worried about that at all.

## Changelog

[Contains]

+ Assorted Event mobs
+ Some Event related turfs
+ Shitcode
+ Lots of kitbashed spritework
+ Some custom soundwork

:cl:
add: Assorted Event mobs
add: Some Event related turfs
add: Event mob related sounds
add: A bunch of related icons
/:cl:

2024-12-29 19:47 UTC, Kashargul requested changes
Our maps belong into modular_chomp/maps

no new _ch files, those all go to modular_chomp without the addition

2024-12-29 19:49 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs_ch.dm
> +	tt_desc = "<font color='#A663FF'><span class='sinister' style='font-size:12pt'><i><b>!@ %*!($*- COME TO ME. @#%*(@#%</b></i></span></font>"
old tags are no longer allowed. Use the span colours

2024-12-29 19:49 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs_ch.dm
> +	desc = "A massive polished stone structure with twelve sides. <font color='#A663FF'><span class='sinister' style='font-size:15pt'><i><b>It throbs with unknown energies, your mere presence near it ma
old tags are no longer allowed. Use the span colours

2024-12-29 19:50 UTC, Kashargul requested changes

2024-12-29 19:50 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs_ch.dm
> +	desc = "<font color='#A663FF'><span class='sinister' style='font-size:15pt'><i><b>A towering, polished stone spire of dark psychic energy, with four sides, covered in constantly shifting inscription
^see above

2024-12-29 19:50 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs_ch.dm
> +	tt_desc = "<font color='#A663FF'><span class='sinister' style='font-size:12pt'><i><b>!@ %*!($*- COME TO ME. @#%*(@#%</b></i></span></font>"
^see above

2024-12-29 19:50 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs_ch.dm
> +				L.visible_message(span_warning("<font color='#A663FF'><span class='sinister' style='font-size:14pt'><i><b>[src] pulses ominously at [L], forcefully pushing them away with psychic energy as they t
^see above, same for <b> is now span_bold()

2024-12-29 21:53 UTC, SilencedMP5A5 commented
think i fixed everything! have done thorough testing as well <3

2024-12-30 00:22 UTC, Kashargul requested changes
or if you don't wanti t danger sortged, at least wrap it by an infoplain

2024-12-30 00:22 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +				to_chat(H,span_red("The overwhelming psychic influence from \the [src] makes your senses reel!"))
span_danger

2024-12-30 00:22 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +				to_chat(H,span_red("[pick(obelisk_lure_messages)]"))
span_danger

2024-12-30 01:16 UTC, Kashargul requested changes

2024-12-30 01:16 UTC, Kashargul commented on sound/effects/carrev.ogg
Just saw that we have this outside modular

modular_chomp\sound\effects

2024-12-30 01:26 UTC, SilencedMP5A5 commented on sound/effects/carrev.ogg
?

2024-12-30 01:26 UTC, SilencedMP5A5 commented on sound/effects/carrev.ogg
oh fuc

2024-12-30 03:42 UTC, SilencedMP5A5 commented
anything else? <3

2025-01-01 13:11 UTC, Kashargul requested changes

2025-01-01 13:11 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +	sleep(5)
no sleeps, addTimer(CALLBACK

2025-01-01 13:11 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +	..()
Do we need to do this on New? Or can we use Initialize just fine as we are the furthest child

2025-01-01 13:11 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +		for(var/i = 1 to delay)
For the sake of god. No. See phoron spiders, use animate and timers

2025-01-01 13:11 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +	spawn(0)
see above

2025-01-01 13:11 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +		for(var/i = 1 to delay)
see above

2025-01-01 20:19 UTC, SilencedMP5A5 commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +	..()
i have no idea

2025-01-01 20:24 UTC, Kashargul commented on modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/blackholemobs.dm
> +	..()
Change it to Initialize and test if the mob spawns resized

2025-01-01 21:29 UTC, SilencedMP5A5 commented
some fuckery occurred, whoops

2025-01-02 07:28 UTC, merged